### ISSUE TITLE
Other solution

### ISSUE THREAD

**Issue by dannycolin** [jbtronics/CrookedStyleSheets#9]
An other solution would be to block the ability to load dynamic content like php file.

**Comment by jbtronics** [comment]
The problem is that a browser can not decide if a page is dynamic... The Webbrowser can Server the php file as a file with .html extension and then the browser can not detect if the page was static or dynamic...

**Comment by dannycolin** [comment]
I don't know if it's possible with a browser but it's possible to detect the filetype by analysing the content. So hypothetically, could we download the file, analyse it and execute it if it didn't contain stuff like <?php ?> ?

**Comment by treffynnon** [comment]
PHP is executed server side so you get the output and not the source. It can send headers and content that make it completely indistinguishable from a plain png/txt/html/etc file.
